# Generated by Django 3.1.6 on 2022-02-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TOKEN', to='MyDiaryapp.signup')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
    ]
