# Generated by Django 3.1.6 on 2022-02-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiaryapp', '0003_auto_20220218_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
