# Generated by Django 3.1.6 on 2022-02-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiaryapp', '0004_auto_20220218_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
